version: "3.8"

services:
  appsmith:
    # Собираем образ из корня, Dockerfile там же
    build:
      context: .
      dockerfile: Dockerfile          # ← Этот (НЕ base.dockerfile)
    image: appsmith-custom:latest     # Чтобы потом можно было push/pull
    container_name: appsmith
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    # Монтируем ХОСТОВУЮ папку (она НЕ в репозитории)
    volumes:
      - /home/ubuntu/stacks:/appsmith-stacks

    # DNS по желанию
    dns:
      - 8.8.8.8
      - 1.1.1.1

    environment:
      APPSMITH_SUPABASE_URL: ${APPSMITH_SUPABASE_URL}
      APPSMITH_SUPABASE_ANON: ${APPSMITH_SUPABASE_ANON}
      APPSMITH_DASHBOARD_URL: ${APPSMITH_DASHBOARD_URL}
      APPSMITH_CUSTOM_DOMAIN: ${APPSMITH_CUSTOM_DOMAIN}
