version: '3.8'

services:
  appsmith:
    image: appsmith-custom:latest
    container_name: appsmith
    restart: unless-stopped
    command: ["/opt/appsmith/start_app.sh"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/stacks:/appsmith-stacks
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      APPSMITH_SUPABASE_URL: ${APPSMITH_SUPABASE_URL}
      APPSMITH_SUPABASE_ANON: ${APPSMITH_SUPABASE_ANON}
      APPSMITH_DASHBOARD_URL: ${APPSMITH_DASHBOARD_URL}
      APPSMITH_CUSTOM_DOMAIN: ${APPSMITH_CUSTOM_DOMAIN}